id: Entity Enrichment - Phishing
version: -1
name: Entity Enrichment - Phishing
fromversion: 4.1.0
description: Enrich entities using one or more integrations
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cdd6228a-7feb-4386-8ab1-7dfdf77d99c2
    type: start
    task:
      id: cdd6228a-7feb-4386-8ab1-7dfdf77d99c2
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "9"
      - "11"
      - "13"
      - "17"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 67
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 00b1e9e8-71c6-4519-8893-851545e1fe14
    type: playbook
    task:
      id: 00b1e9e8-71c6-4519-8893-851545e1fe14
      version: -1
      name: URL Enrichment - Generic
      description: |-
        Enrich URL using one or more integrations.

        URL enrichment includes:
        * Verify URL SSL
        * Threat information
        * URL reputaiton
        * Take URL screenshot
      playbookName: URL Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      GetReputation:
        simple: "True"
      Rasterize:
        simple: "True"
      VerifyURL:
        simple: "True"
      url:
        complex:
          root: inputs.url
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 386
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: d0f2162f-3ab7-4a29-850c-e12f15ec6af2
    type: playbook
    task:
      id: d0f2162f-3ab7-4a29-850c-e12f15ec6af2
      version: -1
      name: Email Address Enrichment - Generic
      description: Get email address reputation using one or more integrations
      playbookName: Email Address Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      Domain: {}
      Email:
        complex:
          root: inputs.Email
      GetReputation:
        simple: "True"
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 386
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: 5799a021-f77c-457b-85bc-e362b7ff4b43
    type: playbook
    task:
      id: 5799a021-f77c-457b-85bc-e362b7ff4b43
      version: -1
      name: Domain Enrichment - Generic
      description: Enrich Domain using one or more integrations
      playbookName: Domain Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      Domain:
        simple: ${inputs.Domain}
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 549
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 587c3b81-99c9-45b4-8755-26af4808bf72
    type: playbook
    task:
      id: 587c3b81-99c9-45b4-8755-26af4808bf72
      version: -1
      name: File Enrichment - Generic
      description: |-
        Enrich a file using one or more integrations.

        File enrichment includes:
        * File history
        * Threat information
        * File reputation
      playbookName: File Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      MD5:
        complex:
          root: inputs.MD5
      SHA1:
        complex:
          root: inputs.SHA1
      SHA256:
        complex:
          root: inputs.SHA256
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: 38007764-1687-47b1-8490-0f3cded9dc95
    type: title
    task:
      id: 38007764-1687-47b1-8490-0f3cded9dc95
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 821
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: 3cb6ebba-40c7-4f8f-859d-218977d7564f
    type: playbook
    task:
      id: 3cb6ebba-40c7-4f8f-859d-218977d7564f
      version: -1
      name: IP Enrichment - External - Generic
      description: |-
        Enrich IP using one or more integrations.

        IP enrichment includes:
        * Resolve IP to Hostname (DNS)
        * Threat information
        * Separate internal and external addresses
        * IP reputation
        * For internal addresses, get host information
      playbookName: IP Enrichment - External - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      GetReputation:
        complex:
          root: inputs.GetReputation
      IP:
        complex:
          root: inputs.IP
          transformers:
          - operator: uniq
      InternalRange: {}
      ResolveIP:
        complex:
          root: inputs.ResolveIP
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 819,
        "width": 810,
        "x": 50,
        "y": 67
      }
    }
  }
inputs:
- key: IP
  value:
    complex:
      root: IP
      accessor: Address
      transformers:
      - operator: uniq
  required: false
  description: The IP addresses to enrich
- key: InternalRange
  value: {}
  required: false
  description: The internal range to check against the IPs
- key: MD5
  value:
    complex:
      root: File
      accessor: MD5
      transformers:
      - operator: uniq
  required: false
  description: File MD5 to enrich
- key: SHA256
  value:
    complex:
      root: File
      accessor: SHA256
  required: false
  description: File SHA256 to enrich
- key: SHA1
  value:
    complex:
      root: File
      accessor: SHA1
  required: false
  description: File SHA1 to enrich
- key: url
  value:
    complex:
      root: URL
      accessor: Data
  required: false
  description: url to enrich
- key: Email
  value:
    complex:
      root: Account
      accessor: Email.Address
  required: false
  description: The email addresses to enrich
- key: Hostname
  value:
    complex:
      root: Endpoint
      accessor: Hostname
  required: false
  description: The hostname to enrich
- key: Username
  value:
    complex:
      root: Account
      accessor: Username
  required: false
  description: The Username to enrich
- key: Domain
  value:
    complex:
      root: Domain
      accessor: Name
  required: false
  description: The domain name to enrich
- key: ResolveIP
  value:
    simple: "False"
  required: false
  description: Determines whether the IP Enrichment - Generic playbook should convert
    IP addresses to hostnames using a DNS query. You can set this to either True or
    False.
outputs:
- contextPath: Account
  description: The Account's object
  type: unknown
- contextPath: Account.ID
  description: The unique Account DN (Distinguished Name)
  type: string
- contextPath: Domain
  description: The domain objects
  type: unknown
- contextPath: URL
  description: The URL's object
  type: unknown
- contextPath: URL.Malicious
  description: whether url was detected as malicious
  type: unknown
- contextPath: URL.Vendor
  description: name of vendor who labeled as malicious
  type: string
- contextPath: URL.Description
  description: additional info on the url
  type: string
- contextPath: URL.Address
  description: The enriched URL
  type: string
- contextPath: Account.Email.Address
  description: The Email account full address
  type: string
- contextPath: IP
  description: The IP objects
  type: unknown
- contextPath: Account.Email.Domain
  description: The Email account domain
  type: string
- contextPath: Account.Email.NetworkType
  description: The Email account NetworkType (could be Internal/External)
  type: string
- contextPath: Account.Email.Username
  description: The Email account username
  type: string
- contextPath: Account.Email.Distance.Domain
  description: The compared domain
  type: unknown
- contextPath: Account.Email.Distance.Value
  description: 'The distance between the email domain and the compared domain '
  type: string
- contextPath: Account.Type
  description: Type of the Account entity
  type: string
- contextPath: Account.Username
  description: The Account username
  type: string
- contextPath: Account.Email
  description: The email address associated with the Account
- contextPath: Account.Groups
  description: The groups the Account is part of
  type: unknown
- contextPath: Account.DisplayName
  description: The Account display name
  type: string
- contextPath: Account.Manager
  description: The Account's manager
  type: string
- contextPath: File
  description: The File's object
  type: unknown
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: Endpoint
  description: The Endpoint's object
  type: unknown
- contextPath: Endpoint.Hostname
  description: The hostname to enrich
  type: string
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: List of endpoint IP addresses
- contextPath: Endpoint.MAC
  description: List of endpoint MAC addresses
- contextPath: Endpoint.Domain
  description: Endpoint domain name
  type: string
- contextPath: DBotScore
  description: The Indicator's object
  type: unknown
- contextPath: DBotScore.Indicator
  description: The Indicator
  type: string
- contextPath: DBotScore.Type
  description: The Indicator Type
  type: string
- contextPath: DBotScore.Vendor
  description: The DBot score vendor
  type: string
- contextPath: DBotScore.Score
  description: The DBot score
  type: number
releaseNotes: "A new entity enrichment playbook for phishing to avoid enrichment of irrelevant entities."
tests:
  - no test - each entity has or will have its own test