id: File Enrichment - Generic
version: -1
name: File Enrichment - Generic
fromversion: 4.1.0
description: |-
  Enrich a file using one or more integrations.

  File enrichment includes:
  * File history
  * Threat information

  File reputation will be done using auto-extract in every task.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6fa65b00-15dc-4cab-8b4e-7ab8e2720215
    type: start
    task:
      id: 6fa65b00-15dc-4cab-8b4e-7ab8e2720215
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
      - "19"
      - "24"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 735,
          "y": -90
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: d2deb7de-75cc-4f33-8ba3-6f83370096f8
    type: title
    task:
      id: d2deb7de-75cc-4f33-8ba3-6f83370096f8
      version: -1
      name: Done
      type: title
      description: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 735,
          "y": 780
        }
      }
    note: false
    timertriggers: []
  "19":
    id: "19"
    taskid: d92660c2-aae0-4955-8860-55b5a873ea84
    type: title
    task:
      id: d92660c2-aae0-4955-8860-55b5a873ea84
      version: -1
      name: File history
      type: title
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 420,
          "y": 90
        }
      }
    note: false
    timertriggers: []
  "21":
    id: "21"
    taskid: 17c2e4fc-dd7d-47ca-8b80-fadd154f6b07
    type: regular
    task:
      id: 17c2e4fc-dd7d-47ca-8b80-fadd154f6b07
      version: -1
      name: Search for file history in Palo Alto AppFramework
      description: Search for file history in the Palo Alto AppFramework integration.
      script: Palo Alto AppFramework|||pan-appframework-search-by-file-hash
      type: regular
      iscommand: true
      brand: Palo Alto AppFramework
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      SHA256:
        complex:
          root: inputs.SHA256
          transformers:
          - operator: uniq
      endTime: {}
      logsAmount: {}
      rangeValue: {}
      startTime: {}
      timeRange: {}
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 412.5,
          "y": 590
        }
      }
    note: false
    timertriggers: []
  "23":
    id: "23"
    taskid: d690278a-878c-4cc2-8a66-461ed5e82bf1
    type: condition
    task:
      id: d690278a-878c-4cc2-8a66-461ed5e82bf1
      version: -1
      name: Is Palo Alto AppFramework enabled?
      description: Checks if there is an active instance of Palo Alto AppFramework.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "21"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Palo Alto AppFramework
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 412.5,
          "y": 390
        }
      }
    note: false
    timertriggers: []
  "24":
    id: "24"
    taskid: 9b849bc8-3a9b-46c5-802e-2fc25b7b1761
    type: title
    task:
      id: 9b849bc8-3a9b-46c5-802e-2fc25b7b1761
      version: -1
      name: Threat information
      type: title
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "29"
      - "25"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1035,
          "y": 90
        }
      }
    note: false
    timertriggers: []
  "25":
    id: "25"
    taskid: c12d3eb4-8bfa-4f31-840b-ca2103689d7b
    type: condition
    task:
      id: c12d3eb4-8bfa-4f31-840b-ca2103689d7b
      version: -1
      name: Is there a SHA-256 hash?
      description: Check if there is a SHA-256 hash in context.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "27"
      - "23"
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.SHA256
            iscontext: true
    view: |-
      {
        "position": {
          "x": 735,
          "y": 215
        }
      }
    note: false
    timertriggers: []
  "27":
    id: "27"
    taskid: c3014a30-73f6-43b1-8aa9-e9029efae876
    type: condition
    task:
      id: c3014a30-73f6-43b1-8aa9-e9029efae876
      version: -1
      name: Is Cylance Protect v2 enabled?
      description: Checks if there is an active instance of Cylance Protect v2.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "28"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Cylance Protect v2
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1035,
          "y": 390
        }
      }
    note: false
    timertriggers: []
  "28":
    id: "28"
    taskid: a23ba0de-d360-4d11-81dc-b05661e2a6a1
    type: regular
    task:
      id: a23ba0de-d360-4d11-81dc-b05661e2a6a1
      version: -1
      name: Get threat information from Cylance Protect v2
      description: Get threat information from the Cylance Protect v2 integration.
      script: Cylance Protect v2|||cylance-protect-get-threat
      type: regular
      iscommand: true
      brand: Cylance Protect v2
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      sha256:
        complex:
          root: inputs.SHA256
          transformers:
          - operator: uniq
    reputationcalc: 2
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1035,
          "y": 590
        }
      }
    note: false
    timertriggers: []
  "29":
    id: "29"
    taskid: 4e009c34-dfb2-4626-8c6e-b8da7850d084
    type: playbook
    task:
      id: 4e009c34-dfb2-4626-8c6e-b8da7850d084
      version: -1
      name: File Enrichment - Virus Total Private API
      description: Get file information using the Virus Total Private API integration.
      playbookName: File Enrichment - Virus Total Private API
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      MD5:
        complex:
          root: inputs.MD5
          transformers:
          - operator: uniq
      SHA1:
        complex:
          root: inputs.SHA1
          transformers:
          - operator: uniq
      SHA256:
        complex:
          root: inputs.SHA256
          transformers:
          - operator: uniq
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 1450,
          "y": 390
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {
      "23_21_yes": 0.52,
      "23_7_#default#": 0.5,
      "25_23_yes": 0.52,
      "25_27_yes": 0.59,
      "25_7_#default#": 0.43,
      "27_28_yes": 0.57,
      "27_7_#default#": 0.52
    },
    "paper": {
      "dimensions": {
        "height": 935,
        "width": 1417.5,
        "x": 412.5,
        "y": -90
      }
    }
  }
inputs:
- key: MD5
  value:
    complex:
      root: File
      accessor: MD5
      transformers:
      - operator: uniq
  required: false
  description: File MD5 hash to enrich.
- key: SHA256
  value:
    complex:
      root: File
      accessor: SHA256
      transformers:
      - operator: uniq
  required: false
  description: File SHA-256 hash to enrich.
- key: SHA1
  value:
    complex:
      root: File
      accessor: SHA1
      transformers:
      - operator: uniq
  required: false
  description: File SHA-1 hash to enrich.
outputs:
- contextPath: DBotScore.Indicator
  description: The tested indicator
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: DBotScore
  description: The DBotScore's object
  type: unknown
- contextPath: File
  description: The file's object
  type: unknown
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: File.VirusTotal.Scans
  description: the scan object
  type: unknown
- contextPath: File.VirusTotal.Scans.Source
  description: Scan vendor for this hash
- contextPath: File.VirusTotal.Scans.Detected
  description: Scan detection for this hash (True,False)
- contextPath: File.VirusTotal.Scans.Result
  description: Scan result for this hash - signature, etc.
releaseNotes: "Improved indicator uniqueness. Removed redundant subplaybook. Simplified conditions & structure."
tests:
  - File Enrichment - Generic Test